server:
  port: 8000
  servlet:
    contextPath: /ucundinamarca/api/v1
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: miguel333mmm@gmail.com
    password: vbsrcmmirbkkpauk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    reporteador:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@172.16.8.62:1521:DBUNICUN
      username: REPORTEADOR
      password: s3s33@4U14lak46ZM0
    camposaprendizajeudec:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@172.16.8.62:1521:DBUNICUN
      username: CAMPOSAPRENDIZAJEUDEC
      password: p1a4s2$sUa333V23gK
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
