server:
   port: 8000
   servlet:
      contextPath: /ucundinamarca/api/v1
spring:
   mail:
      host: smtp.gmail.com
      port: 587
      username: miguel333mmm@gmail.com
      password: vbsrcmmirbkkpauk
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin
   jpa:
      properties:
         hibernate.jdbc.lob.non_contextual_creation: false
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect # Add this line for PostgreSQL dialect
      hibernate:
         ddl-auto: update # You might want to set this as well
   datasource:
      reporteador:
         driver-class-name: oracle.jdbc.driver.OracleDriver
         url: jdbc:oracle:thin:@172.16.8.62:1521:DBUNICUN
         username: REPORTEADOR
         password: s3s33@4U14lak46ZM0
      camposAprendizajeUdec:
         driver-class-name: oracle.jdbc.driver.OracleDriver
         url: jdbc:oracle:thin:@172.16.8.62:1521:DBUNICUN
         username: CAMPOSAPRENDIZAJEUDEC
         password: p1a4s2$sUa333V23gK
integration:
   amq:
      url: tcp://localhost:61616
      user: admin
      password: admin
      maxConnections: 8
      concurrentConsumers: 10
   queues:
      activate: activate
      recuperarPassword: resetpassword
logging:
   level:
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG